# Generated by Django 4.2.7 on 2024-08-21 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPToBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('is_active', models.BooleanField(default=False, verbose_name='is blocked')),
                ('current_ip', models.CharField(max_length=150, verbose_name='current user ip')),
            ],
            options={
                'verbose_name': 'IP To Block',
                'verbose_name_plural': 'IPs To Block',
                'db_table': 'apps_common_serverhttp_iptoblock',
            },
        ),
    ]
