# Generated by Django 4.2.7 on 2024-08-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverhttp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptoblockmodel',
            options={'verbose_name': 'IP Blocked', 'verbose_name_plural': 'IPs Blocked'},
        ),
        migrations.AddField(
            model_name='iptoblockmodel',
            name='reason',
            field=models.CharField(choices=[('RA', 'Attempts to obtain forbidden urls'), ('SK', 'Multiple failed security key entry attempts')], default='RA', max_length=4, verbose_name='reason'),
        ),
    ]
