# Generated by Django 4.2.13 on 2024-08-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverhttp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptoblockmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is blocked'),
        ),
    ]
