# Generated by Django 4.2.7 on 2024-08-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverhttp', '0004_rename_iptoblockmodel_ipblockedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPBlockedModel',
        ),
    ]
