# Generated by Django 4.2.7 on 2024-08-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userloginattempt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLoginAttempt',
            new_name='UserLoginAttemptModel',
        ),
        migrations.AlterModelTable(
            name='userloginattemptmodel',
            table='apps_project_common_users_userloginattempt',
        ),
    ]
