# Generated by Django 4.2.7 on 2024-08-23 05:29

import apps.project.specific.assets.signals
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('asset_img', models.ImageField(blank=True, null=True, upload_to=apps.project.specific.assets.signals.assets_directory_path, verbose_name='img')),
                ('name', models.CharField(max_length=255, verbose_name='english name')),
                ('es_name', models.CharField(max_length=255, verbose_name='spanish name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('asset_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('emission', models.CharField(blank=True, max_length=50, null=True, verbose_name='emission')),
                ('quantity_type', models.CharField(choices=[('U', 'Units'), ('C', 'Containers'), ('B', 'Boxes'), ('O', 'Other')], default='U', max_length=2, verbose_name='quantity type')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='total lump sum')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assetcategory', to='categories.assetcategorymodel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'apps_project_specific_assets_asset',
                'unique_together': {('name', 'quantity_type')},
            },
        ),
        migrations.CreateModel(
            name='AssetStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('S', 'Sold'), ('O', 'Other')], default='R', max_length=2, verbose_name='status')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='price')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetstatus_asset', to='assets.assetmodel', verbose_name='Assets')),
            ],
            options={
                'verbose_name': 'Assets Status',
                'verbose_name_plural': 'Assets Statuses',
                'db_table': 'apps_project_specific_assets_status',
            },
        ),
    ]
