# Generated by Django 4.2.7 on 2024-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='total_quantity',
            field=models.BigIntegerField(default=0, verbose_name='total lump sum'),
        ),
    ]
