# Generated by Django 4.2.7 on 2024-08-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assetmodel_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='boxes_per_container',
            field=models.BigIntegerField(default=0, verbose_name='boxes per container'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='observations',
            field=models.TextField(default='', verbose_name='observations'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='units_per_box',
            field=models.BigIntegerField(default=0, verbose_name='units per box'),
        ),
    ]
