# Generated by Django 4.2.7 on 2024-08-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetmodel_boxes_per_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='observations',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observations'),
        ),
    ]
