# Generated by Django 4.2.7 on 2024-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_assetmodel_asset_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmodel',
            options={'ordering': ['default_order', 'es_name', '-created'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AddField(
            model_name='assetstatusmodel',
            name='buyer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='buyer'),
        ),
        migrations.AddField(
            model_name='assetstatusmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='assetstatusmodel',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='observations'),
        ),
    ]
