# Generated by Django 4.2.7 on 2024-08-29 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_delete_assetlocationmodel'),
        ('assets', '0006_alter_assetmodel_options_assetstatusmodel_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_asset', to='assets.assetmodel', verbose_name='Assets')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_location', to='locations.locationmodel', verbose_name='location')),
            ],
            options={
                'verbose_name': 'Assets Location',
                'verbose_name_plural': 'Assets Locations',
                'db_table': 'apps_project_specific_locations_assetlocation',
            },
        ),
        migrations.RemoveField(
            model_name='assetstatusmodel',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='assetstatusmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='assetstatusmodel',
            name='status',
        ),
        migrations.CreateModel(
            name='AssetStatusReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('S', 'Sold'), ('O', 'Other')], default='R', max_length=2, verbose_name='status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetlocationmodel', verbose_name='supplier')),
            ],
            options={
                'ordering': ['default_order'],
                'abstract': False,
            },
        ),
    ]
