# Generated by Django 4.2.7 on 2024-08-29 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_delete_assetlocationmodel'),
        ('assets', '0007_assetlocationmodel_remove_assetstatusmodel_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstatusreferencemodel',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetstatusreferencemodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationmodel', verbose_name='supplier'),
        ),
    ]
