# Generated by Django 4.2.7 on 2024-08-29 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_locationmodel_unique_together'),
        ('assets', '0008_assetstatusreferencemodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetstatusreferencemodel',
            options={'verbose_name': 'Assets Status', 'verbose_name_plural': 'Assets Statuses'},
        ),
        migrations.AlterField(
            model_name='assetstatusreferencemodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetstatusreference_location', to='locations.locationmodel', verbose_name='supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='assetlocationmodel',
            unique_together={('asset', 'location')},
        ),
        migrations.AlterModelTable(
            name='assetlocationmodel',
            table='apps_project_specific_assets_assetlocation',
        ),
        migrations.AlterModelTable(
            name='assetstatusreferencemodel',
            table='apps_project_specific_assets_statusreference',
        ),
    ]
