# Generated by Django 4.2.7 on 2024-08-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetstatusreferencemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetmodel',
            unique_together={('name', 'quantity_type')},
        ),
    ]
