# Generated by Django 4.2.7 on 2024-08-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_assetmodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetstatusreferencemodel',
            name='asset_status',
        ),
        migrations.RemoveField(
            model_name='assetstatusreferencemodel',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='AssetLocationModel',
        ),
        migrations.DeleteModel(
            name='AssetStatusModel',
        ),
        migrations.DeleteModel(
            name='AssetStatusReferenceModel',
        ),
    ]
