# Generated by Django 4.2.7 on 2024-08-23 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('reference', models.CharField(max_length=150, verbose_name='reference')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('continent', models.CharField(choices=[('AS', 'Asia'), ('NA', 'North America'), ('CA', 'Central America'), ('SA', 'South America'), ('AF', 'Africa'), ('AN', 'Antarctica'), ('EU', 'Europe'), ('OC', 'Oceania')], default='EU', max_length=3, verbose_name='continent')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'apps_project_specific_locations_location',
            },
        ),
        migrations.CreateModel(
            name='AssetLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_asset', to='assets.assetmodel', verbose_name='Assets')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_location', to='locations.locationmodel', verbose_name='location')),
            ],
            options={
                'verbose_name': 'Assets Location',
                'verbose_name_plural': 'Assets Locations',
                'db_table': 'apps_project_specific_locations_assetlocation',
            },
        ),
    ]
