# Generated by Django 4.2.7 on 2024-08-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetLocationModel',
        ),
    ]
