# Generated by Django 4.2.7 on 2024-08-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_delete_assetlocationmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationmodel',
            unique_together={('reference', 'continent', 'owner')},
        ),
    ]
