# Generated by Django 4.2.7 on 2024-08-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_locationmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationmodel',
            unique_together=set(),
        ),
    ]
