# Generated by Django 4.2.7 on 2024-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_assetlocationmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocationmodel',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='amount'),
        ),
    ]
