# Generated by Django 4.2.7 on 2024-08-30 00:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_assetlocationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='price')),
                ('buyer', models.CharField(blank=True, max_length=255, null=True, verbose_name='buyer')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observations')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Assets Status',
                'verbose_name_plural': 'Assets Statuses',
                'db_table': 'apps_project_specific_status_status',
            },
        ),
        migrations.CreateModel(
            name='AssetStatusReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('S', 'Sold'), ('O', 'Other')], default='R', max_length=2, verbose_name='status')),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('asset_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetstatus_references', to='status.assetstatusmodel', verbose_name='asset status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetstatusreference_location', to='locations.assetlocationmodel', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Assets Status Reference',
                'verbose_name_plural': 'Assets Statuses References',
                'db_table': 'apps_project_specific_status_statusreference',
            },
        ),
    ]
