# Generated by Django 4.2.7 on 2024-09-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_assetstatusmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstatusmodel',
            name='total_quantity',
            field=models.BigIntegerField(default=0, verbose_name='total lump sum'),
        ),
    ]
