# Generated by Django 4.2.7 on 2024-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategorymodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='category'),
        ),
    ]
