# Generated by Django 4.2.7 on 2024-10-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificatemodel_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemodel',
            name='step',
            field=models.IntegerField(default=1, help_text='Step of the certificate', verbose_name='Step'),
        ),
    ]
