# Generated by Django 4.2.7 on 2024-10-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificatemodel_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Citizen ID (CC)'), ('CE', 'Foreigner ID (CE)'), ('PPT', 'Special Residence Permit (PPT)'), ('TI', 'Identity Card (TI)'), ('PA', 'Passport (PA)'), ('RC', 'Civil Registry (RC)'), ('NIT', 'Tax Identification Number (NIT)'), ('RUT', 'Single Tax Registry (RUT)'), ('CD', 'Diplomatic ID Card (CD)')], default='CC', max_length=4, verbose_name='Document type'),
        ),
    ]
