# Generated by Django 4.2.7 on 2024-08-21 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('bond_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('emission', models.CharField(blank=True, max_length=50, null=True, verbose_name='emission')),
                ('quantity_type', models.CharField(choices=[('U', 'Units'), ('C', 'Containers'), ('B', 'Boxes'), ('O', 'Other')], default='U', max_length=2, verbose_name='quantity type')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='total lump sum')),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('S', 'Sold'), ('O', 'Other')], default='A', max_length=2, verbose_name='status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_bondcategory', to='categories.bondcategorymodel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
                'db_table': 'apps_project_specific_bonds_bond',
            },
        ),
    ]
