# Generated by Django 4.2.7 on 2024-08-22 00:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondmodel',
            name='status',
        ),
        migrations.CreateModel(
            name='BondStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('S', 'Sold'), ('O', 'Other')], default='A', max_length=2, verbose_name='status')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bondstatus_bond', to='bonds.bondmodel', verbose_name='bond')),
            ],
            options={
                'verbose_name': 'Bond Status',
                'verbose_name_plural': 'Bond Statuses',
                'db_table': 'apps_project_specific_bonds_status',
            },
        ),
    ]
