# Generated by Django 4.2.7 on 2024-08-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_remove_bondmodel_status_bondstatusmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bondmodel',
            unique_together={('name', 'quantity_type')},
        ),
    ]
