# Generated by Django 4.2.7 on 2024-08-23 05:29

import apps.common.utils.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('buyer_type', models.CharField(choices=[('B', 'Bank'), ('ON', 'Organization'), ('P', 'Private'), ('O', 'Other')], default='P', max_length=3, verbose_name='buyer type')),
                ('buyer_name', apps.common.utils.models.EncryptedCharField(max_length=255, verbose_name='buyer name')),
                ('buyer_country', models.CharField(default='US', max_length=50, verbose_name='country code')),
                ('amount_sold', apps.common.utils.models.EncryptedIntegerField(max_length=255, verbose_name='amount sold')),
                ('sales_type', models.CharField(choices=[('DS', 'Direct Sales'), ('RD', 'RD'), ('O', 'Other')], default='DS', max_length=3, verbose_name='sales type')),
                ('sale_value', apps.common.utils.models.EncryptedDecimalField(max_length=255, verbose_name='sale value')),
                ('sale_currency', models.CharField(choices=[('AED', 'AED, United Arab Emirates Dirham'), ('ARS', 'ARS, Argentine Peso'), ('AUD', 'AUD, Australian Dollar'), ('BRL', 'BRL, Brazilian Real'), ('CAD', 'CAD, Canadian Dollar'), ('CHF', 'CHF, Swiss Franc'), ('CNY', 'CNY, Chinese Yuan'), ('COP', 'COP, Colombian Peso'), ('DKK', 'DKK, Danish Krone'), ('EUR', 'EUR, Euro'), ('GBP', 'GBP, British Pound Sterling'), ('HKD', 'HKD, Hong Kong Dollar'), ('ILS', 'ILS, Israeli New Shekel'), ('INR', 'INR, Indian Rupee'), ('JPY', 'JPY, Japanese Yen'), ('KRW', 'KRW, South Korean Won'), ('MXN', 'MXN, Mexican Peso'), ('MYR', 'MYR, Malaysian Ringgit'), ('NOK', 'NOK, Norwegian Krone'), ('NZD', 'NZD, New Zealand Dollar'), ('PLN', 'PLN, Polish Zloty'), ('RUB', 'RUB, Russian Ruble'), ('SAR', 'SAR, Saudi Riyal'), ('SEK', 'SEK, Swedish Krona'), ('SGD', 'SGD, Singapore Dollar'), ('THB', 'THB, Thai Baht'), ('TRY', 'TRY, Turkish Lira'), ('TWD', 'TWD, New Taiwan Dollar'), ('USD', 'USD, United States Dollar'), ('ZAR', 'ZAR, South African Rand'), ('ZWD', 'ZWD, Zimbabwe Dollar')], default='USD', max_length=4, verbose_name='currency')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_bond', to='assets.assetmodel', verbose_name='asset')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'apps_project_specific_sales_sales',
            },
        ),
    ]
