# Generated by Django 4.2.7 on 2024-08-21 19:57

import apps.common.utils.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('buyer_type', models.CharField(choices=[('B', 'Bank'), ('ON', 'Organization'), ('P', 'Private'), ('O', 'Other')], default='P', max_length=3, verbose_name='buyer type')),
                ('buyer_name', apps.common.utils.models.EncryptedCharField(verbose_name='buyer name')),
                ('buyer_country', models.CharField(blank=True, max_length=10, null=True, verbose_name='country code')),
                ('amount_sold', apps.common.utils.models.EncryptedPositiveIntegerField(verbose_name='amount sold')),
                ('sales_type', models.CharField(choices=[('RD', 'RD'), ('DS', 'Direct Sales'), ('O', 'Other')], default='DS', max_length=3, verbose_name='sales type')),
                ('sale_value', apps.common.utils.models.EncryptedDecimalField(verbose_name='sale value')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_bond', to='bonds.bondmodel', verbose_name='bond')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'apps_project_specific_sales_sales',
            },
        ),
    ]
