# Generated by Django 4.2.13 on 2024-08-22 08:31

import apps.common.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesmodel_sale_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmodel',
            name='amount_sold',
            field=apps.common.utils.models.EncryptedPositiveIntegerField(max_length=255, verbose_name='amount sold'),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='buyer_name',
            field=apps.common.utils.models.EncryptedCharField(max_length=255, verbose_name='buyer name'),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='sale_value',
            field=apps.common.utils.models.EncryptedDecimalField(max_length=255, verbose_name='sale value'),
        ),
    ]
